services:
  db:
    image: postgres:17.3-alpine3.21
    container_name: etl_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=etl
    ports:
      - "5432:5432"
    restart: always